config/routes.rb
HomeBrewSocial::Application.routes.draw do
  devise_for :users

  resources :beers

  root :to=> 'beers#index'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  attr_accessible :description, :name
  validates_presence_of :name
  has_many :ingredients
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :quantity, :unit
  validates_presence_of :name, :quantity, :unit
  belongs_to :beer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable,:validatable, :confirmable
  validates_presence_of :name

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email,:name, :password, :password_confirmation
  has_many :beers
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController

  before_filter :authenticate_user!, except: [:index,:show]
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beers }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @beer = Beer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer }
    end
  end

  # GET /beers/new
  # GET /beers/new.json
  def new
    @beer = Beer.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @beer }
    end
  end

  # GET /beers/1/edit
  def edit
    @beer = Beer.find(params[:id])
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(params[:beer])

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render json: @beer, status: :created, location: @beer }
      else
        format.html { render action: "new" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beers/1
  # PUT /beers/1.json
  def update
    @beer = Beer.find(params[:id])

    respond_to do |format|
      if @beer.update_attributes(params[:beer])
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip Devise :timeout and :timedout flags
      next if type == :timeout
      next if type == :timedout
      type = :success if type == :notice
      type = :error if type == :alert
      text = content_tag(:div,
                         content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                             message, :class => "alert fade in alert-#{type}")
      flash_messages << text if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.haml
= simple_form_for @beer do |f|
  - if @beer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@beer.errors.count, "error")} prohibited this beer from being saved:"
      %ul
        - @beer.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    = f.label :name
    .controls
      = f.text_field :name
  .control-group
    = f.label :description
    .controls
      = f.text_area :description
  .control-group
    .controls
      = f.button :submit, 'Save', class: 'btn btn-primary'

app/views/beers/edit.html.haml
%h1 Editing beer

= render 'form'

= link_to 'Show', @beer
\|
= link_to 'Back', beers_path

app/views/beers/index.html.haml
%header
  %h1 Listing beers

%table.table.table-bordered
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th
  %tbody
    - @beers.each do |beer|
      %tr
        %td= beer.name
        %td= beer.description
        %td= link_to 'Show', beer
        %td= link_to 'Edit', edit_beer_path(beer)
        %td= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Beer', new_beer_path

app/views/beers/new.html.haml
%h1 New beer

= render 'form'

= link_to 'Back', beers_path

app/views/beers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @beer.name
%p
  %b Description:
  = @beer.description

= link_to 'Edit', edit_beer_path(@beer)
\|
= link_to 'Back', beers_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "HomeBrewSocial"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href=root_path)
            %span.icon-beer
            ='HomeBrewSocial'
          .container.nav-collapse
            %ul.nav
              -if user_signed_in?
                %li= link_to current_user.name, edit_user_registration_path
                %li= link_to "Log Out", destroy_user_session_path, method: :delete
              -else
                %li= link_to "Sign Up", new_user_registration_path
                %li= link_to "Log In", new_user_session_path

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Grey Rock Software 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"